name: SurvivalEnvelope
main: org.rtdxe.survivalEnvelope.SurvivalEnvelope
version: 2.0
api-version: 26.1.2
author: RTDxE
description: >
  Enhances world danger through unique mob variants and aggressive behaviour overhauls.

commands:
  se:
    description: SurvivalEnvelope admin commands
    usage: /se reload

